language: go
sudo: required
go:
  - 1.5.2
  - 1.6beta1
  - tip
env:
  global:
    - GO_FOR_RELEASE=1.5.2
    - PATH="$GOPATH/bin:$PATH"
  matrix:
    - GOARCH=amd64
install:
  - go get -x github.com/tools/godep
  - godep restore ./...
script:
  - go test ./...
  - go build -ldflags "-linkmode external -extldflags -static"
after_success:
  - travis/docker_image.bash
services:
  - docker
