language: go
sudo: required
go:
  - 1.5.1
  - tip
env:
  global:
    - GO_FOR_RELEASE=1.5.1
  matrix:
    - GOARCH=amd64
install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - go get -x github.com/tools/godep
  - godep restore ./...
script:
  - go test ./...
  - go build
after_success:
  - travis/docker_image.bash
services:
  - docker
after_deploy:
  - "curl -iH 'Content-Type: application/json' --data \"{\\\"source_type\\\": \\\"Branch\\\", \\\"source_name\\\": \\\"${TRAVIS_BRANCH}\\\"}\" -X POST https://registry.hub.docker.com/u/tsuru/bs/trigger/${HUB_TOKEN}/"
