language: go
sudo: false
go:
  - 1.4.3
  - 1.5.1
  - tip
env:
  - GOARCH=amd64
install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - sed -ie 's;git://;https://;' .git/config
  - go get -x github.com/tools/godep
  - godep restore ./...
script:
  - go test ./...
after_success:
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then curl -iH 'Content-Type: application/json' --data \"{\\\"source_type\\\": \\\"Branch\\\", \\\"source_name\\\": \\\"${TRAVIS_BRANCH}\\\"}\" -X POST https://registry.hub.docker.com/u/tsuru/bs/trigger/${HUB_TOKEN}/; fi"
