language: go
sudo: false
go:
  - 1.4.3
  - 1.5.1
  - tip
env:
  - GOARCH=amd64
install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - sed -ie 's;git://;https://;' .git/config
  - go get -x github.com/tools/godep
  - godep restore ./...
script:
  - go test ./...
  - mkdir target
  - go build -o target/bs
deploy:
  provider: s3
  access_key_id: "${ACCESS_KEY_ID}"
  secret_access_key: "${SECRET_ACCESS_KEY}"
  bucket: tsuru
  skip_cleanup: true
  acl: public_read
  local_dir: target
  upload-dir: bs
after_deploy:
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then curl -iH 'Content-Type: application/json' --data \"{\\\"source_type\\\": \\\"Branch\\\", \\\"source_name\\\": \\\"${TRAVIS_BRANCH}\\\"}\" -X POST https://registry.hub.docker.com/u/tsuru/bs/trigger/${HUB_TOKEN}/; fi"
