language: go
sudo: false
go:
  - 1.4
  - 1.5
  - tip
env:
  - GOARCH=amd64
  - GOARCH=386
install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - sed -ie 's;git://;https://;' .git/config
  - go get -x github.com/tools/godep
  - go get -d -t -u -f -x ./... || true
  - godep restore ./...
script:
  - go test ./...
after_success:
  - "curl -H 'Content-Type: application/json' --data '{\"build\": true}' -X POST https://registry.hub.docker.com/u/tsuru/bs/trigger/${HUB_TOKEN}/"
