language: go
sudo: required
go:
  - 1.5.4
  - 1.6.2
  - tip
env:
  global:
    - GO_FOR_RELEASE=1.6.2
    - GO15VENDOREXPERIMENT=1
  matrix:
    - GOARCH=amd64
install:
  - true
script:
  - go test ./...
  - make check-format
  - go build -ldflags "-linkmode external -extldflags -static"
after_success:
  - travis/docker_image.bash
services:
  - docker
matrix:
  allow_failures:
    - go: tip
